### ISSUE TITLE
数据集求助

### ISSUE THREAD

**Issue by Oneteenager** [hunterlew/mstar_deeplearning_project#1]
您好，我再看您的分类data时看到有十类目标，您的图像是经过处理过的，我想问您一下，对于bmp_2,T_72的变种数据您是否有？可否发一份。

**Comment by hunterlew** [comment]
@Oneteenager 
变种数据你是指？建议去mstar官网找找，估计我没有。

**Comment by Oneteenager** [comment]
谢谢您，我是想问您在读取图片时是否对图片有预处理，例如对比度变化等
